export type RandomMovieResponse = {
        keywords: string[],
        backdropUrl: string,
        production: string,
        trailerYoutubeId: string,
        language: string,
        tmdbRating: string,
        title: string,
        cast: string[],
        revenue: string,
        posterUrl: string,
        plot: string,
        genres: string[],
        id: string,
        budget: string,
        languages: string[],
        releaseDate: string,
        director: string,
        awardsSummary: string,
        runtime: string,
        trailerUrl: string,
        releaseYear: string,
        countriesOfOrigin: string[],
        originalTitle: string,
        searchL: string,
        homepage: string,
        status: string
}